// class User{
//     constructor(id,name,password,age){
//         this.id= id;
//         this.age = age;
//          this.name = name;
//         this.password = password;
       
//     }
// }
// class Student{
//     constructor(EnrollmentNumber, Name, SID, SchemaID,
//     Internal1,External1,Internal2,External2,Internal3,External3,Internal4,External4,Internal5,External5,Internal6,External6,Internal7,External7,Internal8,External8,Internal9,External9,Internal10,External10,Internal11,External11,Internal12,External12,
//     PeparID1,Credit1,PeparID2,Credit2,PeparID3,Credit3,PeparID4,Credit4,PeparID5,Credit5,PeparID6,Credit6,PeparID7,Credit7,PeparID8,Credit8,PeparID9,Credit9,PeparID10,Credit10,PeparID11,Credit11,PeparID12,Credit12,
//     Total1,Grade1,Total2,Grade2,Total3,Grade3,Total4,Grade4,Total5,Grade5,Total6,Grade6,Total7,Grade7,Total8,Grade8,Total9,Grade9,Total10,Grade10,Total11,Grade11,Total12,Grade12,
//     CSRemark,
//     Internal1a,Internal2a,Internal3a,Internal4a,Internal5a,Internal6a,Internal7a,Internal8a,Internal9a,Internal10a,Internal11a,Internal12a,
//     Internal1b,Internal2b,Internal3b,Internal4b,Internal5b,Internal6b,Internal7b,Internal8b,Internal9b,Internal10b,Internal11b,Internal12b,
//     Internal1c,Internal2c,Internal3c,Internal4c,Internal5c,Internal6c,Internal7c,Internal8c,Internal9c,Internal10c,Internal11c,Internal12c,

//     Semester1,Semester2,Semester3,Semester4,Semester5,Semester6,Semester7,Semester8,UniversityName,InstitutionCode,InstitutionName,ProgrammeName,ProgrammeCode) {
//     this.EnrollmentNumber = EnrollmentNumber;
//     this.Name = Name;
//     this.SID = SID;
//     this.SchemaID = SchemaID;
//     this.Unive    
//     }
// }
// 'EnrollmentNumber': '00110102715',
//     'Name': 'AAKASH',
//     'SID': 190000083688,
//     'SchemaID': 190272015001,
//     'UniversityName': 'GURU GOVIND SINGH INDRAPRASTHA UNIVERSITY',
//     'InstitutionCode': 101,
//     'InstitutionName': 'AMBEDKAR INSTITUTE OF ADVANCED COMMUNICATION TECHNOLOGIES & RESEARCH (FORMERLY AIT)',
//     'ProgrammeName': 'BACHELOR OF TECHNOLOGY (COMPUTER SCIENCE AND ENGINEERING)',
//     'ProgrammeCode': '027',
//     'Semester1': {},
//     'Semester2': {},
//     'Semester3': {},
//     'Semester4': {},
//     'Semester5': {
//         'Internal1': 15,
//         'External1': 32,
//         'Internal2': 13,
//         'External2': 46,
//         'Internal3': 16,
//         'External3': 35,
//         'Internal4': 17,
//         'External4': 36,
//         'Internal5': 13,
//         'External5': 35,
//         'Internal6': 10,
//         'External6': 43,
//         'Internal7': 26,
//         'External7': 50,
//         'Internal8': 35,
//         'External8': 49,
//         'Internal9': 30,
//         'External9': 46,
//         'Internal10': 24,
//         'External10': 44,
//         'Internal11': 29,
//         'External11': 46,
//         'Internal12': 33,
//         'External12': 44,
//         'PeparID1': 27301,
//         'Credit1': 4,
//         'PeparID2': 98301,
//         'Credit2': 1,
//         'PeparID3': 27303,
//         'Credit3': 4,
//         'PeparID4': 28303,
//         'Credit4': 4,
//         'PeparID5': 27307,
//         'Credit5': 4,
//         'PeparID6': 99311,
//         'Credit6': 3,
//         'PeparID7': 27351,
//         'Credit7': 1,
//         'PeparID8': 98351,
//         'Credit8': 1,
//         'PeparID9': 27353,
//         'Credit9': 1,
//         'PeparID10': 27357,
//         'Credit10': 1,
//         'PeparID11': 28357,
//         'Credit11': 1,
//         'PeparID12': 27359,
//         'Credit12': 1,
//         'Total1': 47,
//         'Grade1': 'C',
//         'Total2': 59,
//         'Grade2': 'B+',
//         'Total3': 51,
//         'Grade3': 'B',
//         'Total4': 53,
//         'Grade4': 'B',
//         'Total5': 48,
//         'Grade5': 'C',
//         'Total6': 53,
//         'Grade6': 'B',
//         'Total7': 76,
//         'Grade7': 'A+',
//         'Total8': 84,
//         'Grade8': 'A+',
//         'Total9': 76,
//         'Grade9': 'A+',
//         'Total10': 68,
//         'Grade10': 'A',
//         'Total11': 75,
//         'Grade11': 'A+',
//         'Total12': 77,
//         'Grade12': 'A+',
//         'CSRemark': 26,
//         'Internal1a': 0,
//         'Internal2a': 0,
//         'Internal3a': 0,
//         'Internal4a': 0,
//         'Internal5a': 0,
//         'Internal6a': 0,
//         'Internal7a': 0,
//         'Internal8a': 0,
//         'Internal9a': 0,
//         'Internal10a': 0,
//         'Internal11a': 0,
//         'Internal12a': 0,
//         'Internal1b': 0,
//         'Internal2b': 0,
//         'Internal3b': 0,
//         'Internal4b': 0,
//         'Internal5b': 0,
//         'Internal6b': 0,
//         'Internal7b': 0,
//         'Internal8b': 0,
//         'Internal9b': 0,
//         'Internal10b': 0,
//         'Internal11b': 0,
//         'Internal12b': 0,
//         'Internal1c': 0,
//         'Internal2c': 0,
//         'Internal3c': 0,
//         'Internal4c': 0,
//         'Internal5c': 0,
//         'Internal6c': 0,
//         'Internal7c': 0,
//         'Internal8c': 0,
//         'Internal9c': 0,
//         'Internal10c': 0,
//         'Internal11c': 0,
//         'Internal12c': 0
//     },
//     'Semester6': {},
//     'Semester7': {},
//     'Semester8': {}
// })
// module.exports = User;